export let thread = [];
export let busy = false;
export let current = 'openrouter';
export let currentModel = '';
export let mode = 'chat';
export let skillsList = [];
export let prepromptsList = [];
export let presetsList = [];
export let allModels = {};
export let ovIdx = -1;
export let ovItems = [];
export let ovOpen = false;
export let slashStart = -1;
export let runCards = new Map();
export let agentStartTime = 0;
export let busySince = 0;
export let currentBubble = null;
export let currentText = '';
export let askCard = null;
export let anon = false;

export function setThread(v) { thread = v; }
export function setBusy(v) { busy = v; }
export function setCurrent(v) { current = v; }
export function setCurrentModel(v) { currentModel = v; }
export function setMode(v) { mode = v; }
export function setSkillsList(v) { skillsList = v; }
export function setPrepromptsList(v) { prepromptsList = v; }
export function setPresetsList(v) { presetsList = v; }
export function setAllModels(v) { allModels = v; }
export function setOvIdx(v) { ovIdx = v; }
export function setOvItems(v) { ovItems = v; }
export function setOvOpen(v) { ovOpen = v; }
export function setSlashStart(v) { slashStart = v; }
export function setRunCards(v) { runCards = v; }
export function setAgentStartTime(v) { agentStartTime = v; }
export function setBusySince(v) { busySince = v; }
export function setCurrentBubble(v) { currentBubble = v; }
export function setCurrentText(v) { currentText = v; }
export function setAskCard(v) { askCard = v; }
export function setAnon(v) { anon = v; }
